# name: Deploy Frontend to S3
# 
# on:
#   push:
#     branches:
#       - main
#     paths:
#       - 'cadastro-front/**'
# 
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
# 
#     steps:
#       - name: Checkout c√≥digo
#         uses: actions/checkout@v3
# 
#       - name: Deploy para o S3
#         uses: jakejarvis/s3-sync-action@master
#         with:
#           args: --delete
#         env:
#           AWS_S3_BUCKET: cadastro-pessoa-front-ana
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           AWS_REGION: us-east-1
#           SOURCE_DIR: 'cadastro-front'
